{
    'name': ' BDcalling Simple User Portal',
    'version': '19.0.1.1',
    'category': 'Portal',
    'sequence': -100,
    'summary': 'Simple User Portal Login System',
    'description': """
        Simple user portal with login system for Odoo 19
    """,
    'author': 'Md Sohag Hossain',
    'depends': [
        'base',
        'website',
        'portal',
        'hr',
        'web',
        'mail',
        'hr_holidays',
        'hr_reward_warning',
        'hr_attendance',
        'account_asset',
        'accountant',
        'stock',
        'hr_work_entry',
    ],
    'data': [
        'security/portal_leave_security.xml',
        'security/ir.model.access.csv',
        'views/wizard_link_portal_employee_views.xml',
        'views/templates.xml',
        # 'views/portal_expense.xml',
        'views/account_asset_view.xml',
        # 'views/asset_assignment_view.xml',
        'views/employee_dasboad_manue_filter.xml',
        'views/portal_apply_leave.xml',
        'views/portal_leave_history.xml',
        'views/portal_team_leader_approvals.xml',
        'views/portal_not_team_leader_404.xml',
        'views/hr_leave_views.xml',
        'views/hr_employee_views.xml',
        # 'views/portal_payslip_templates.xml',
        # 'views/report_payslip.xml',
        'views/employee_profile.xml',
        'views/employee_views.xml',
        # 'views/employeeasset_view.xml',
        'views/hr_leave_allocation_view_inherit.xml',
        'views/menus.xml',
        'views/hr_resign_views.xml',
        'views/portal_resign.xml',
        'views/portal_resign_approvals.xml',
        'views/report_resign.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'portal_login/static/src/css/leave_portal.css',
            'portal_login/static/src/css/responsive.css',
           
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}